print("sumar dos numeros.")
numero_uno = int(input("introduce tu primer numero:"))
numero_dos = int(input("introduce tu segundo numero:"))
print(f"la suma de los numeros es: {numero_uno + numero_dos}")
print("-----------------------------------------------------------")
print("restar dos numeros.")
numero_uno = int(input("introduce tu primer numero:"))
numero_dos = int(input("introduce tu segundo numero:"))
print(f"la resta de los numeros es: {numero_uno - numero_dos}")
print("-----------------------------------------------------------")
print("multiplicar dos numeros.")
numero_uno = int(input("introduce tu primer numero:"))
numero_dos = int(input("introduce tu segundo numero:"))
print(f"la multiplicacion de los numeros es: {numero_uno * numero_dos}")
print("-----------------------------------------------------------")
print("dividir dos numeros.")
numero_uno = int(input("introduce tu primer numero:"))
numero_dos = int(input("introduce tu segundo numero:"))
if numero_dos != 0:
    print(f"la division de los numeros es: {numero_uno / numero_dos}")
else:
    print("No se puede dividir por cero")